export const dataPharmacy = {
  headers: ["Lote", "Nombre", "Presentación", "Expira", "Cantidad", "Editar"],
  rows: [
    {
      id: "1",
      lot_number: "123456",
      name: "Paracetamol",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "2",
      lot_number: "123456",
      name: "Naproxeno",
      expires_at: "12/8/2022",
      pieces: "35",
      edit: "",
    },
    {
      id: "3",
      lot_number: "123456",
      name: "Ibuprofeno",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "4",
      lot_number: "123456",
      name: "Zinc",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "5",
      lot_number: "123456",
      name: "Vitamina C",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "6",
      lot_number: "123456",
      name: "Vitamina D",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "7",
      lot_number: "123456",
      name: "Vitamina E",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
    {
      id: "8",
      lot_number: "123456",
      name: "Vitamina B",
      expires_at: "10/10/2021",
      pieces: "10",
      edit: "",
    },
  ],
  textDisplay: [
    "center",
    "start",
    "center",
    "center",
    "center",
    "center",
  ] as CanvasTextAlign[],
  percentages: [10, 20, 20, 20, 20, 10],
  elements: ["TEXT", "TEXT", "TEXT", "TEXT", "TEXT", "EDIT-BUTTON"],
  medicines: [
    {
      key: "132123112",
      name: "Ibuprofeno",
    },
    {
      key: "132123113",
      name: "Paracetamol",
    },
    {
      key: "132123114",
      name: "Aspirina",
    },
  ],
  historialPrescriptions: [
    {
      folio: 1,
      date: "10/10/2021",
      doctor: "Dr. Juan Perez",
      patient_name: "Emmuel Perez",
      observations: "Observaciones",
      instructions: "1 pastilla cada 8 horas",
      created_at: "10/10/2021",
      supplied_at: "10/10/2021",
      status: "Pendiente",
      actions: "",
    },
  ],
  historialRequests: [
    {
      folio: 1,
      created_at: "10/10/2021",
      name: "Emmuel Perez",
      status: "Pendiente",
    },
  ],
};
