// Generated by https://quicktype.io

export interface IRolesResponse {
  data: Data;
  ok: boolean;
}

export interface Data {
  roles: Role[];
}

export interface Role {
  id: string;
  name: string;
}
