export interface IFixedAssetResponse {
  data: {
    fixed_assets: IFixedAsset[];
  };
}

export interface IFixedAsset {
  id: string;
  description: string;
  model: string;
  brand: string;
  created_at: string;
  updated_at: string;
}

// Generated by https://quicktype.io

export interface IFixedAssetRequestResponse {
  data: Data;
  ok: boolean;
}

export interface Data {
  fixed_assets_requests: FixedAssetsRequest[];
}

export interface FixedAssetsRequest {
  id: string;
  department_id: string;
  department: Department;
  user_id: string;
  user: User;
  created_at: string;
  updated_at: string;
}

export interface Department {
  id: string;
  resposible_user_id: string;
  reponsible_user: ReponsibleUser;
  name: string;
  floor_number: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

export interface ReponsibleUser {
  role_id: string;
  name: string;
  surname: string;
  deleted_at: string;
}

export interface User {
  id: string;
  role_id: string;
  name: string;
  surname: string;
  full_name: string;
  deleted_at: string;
}

// Generated by https://quicktype.io

export interface IRequestIDResponse {
  data: Data;
  ok: boolean;
}

export interface Data {
  fixed_assets_request: FixedAssetsRequestID;
}

export interface FixedAssetsRequestID {
  id: string;
  department_id: string;
  department: Department;
  fixed_assets: FixedAsset[];
  user_id: string;
  user: User;
  created_at: string;
  updated_at: string;
}

export interface Department {
  id: string;
  resposible_user_id: string;
  reponsible_user: ReponsibleUser;
  name: string;
  floor_number: string;
  created_at: string;
  updated_at: string;
  deleted_at: null;
}

export interface ReponsibleUser {
  role_id: string;
  name: string;
  surname: string;
  deleted_at: string;
}

export interface FixedAsset {
  id: string;
  fixed_asset_id: string;
  details: {
    key: string;
    description: string;
    model: string;
    brand: string;
    series: string;
  };
  fixed_assets_request_id: string;
}

export interface User {
  id: string;
  role_id: string;
  name: string;
  surname: string;
  full_name: string;
  deleted_at: string;
}
